@host = https://weatherimageapp-win-gdhah5b9graacuh8.polandcentral-01.azurewebsites.net

###
# 1) Health check
GET {{host}}/api/health
Accept: application/json

###
# 2) Start a new job
# response is named so it can be reused as the jobId below
# @name startJob
POST {{host}}/api/jobs/start
Content-Type: application/json

{}

###
# 3) Get status for the job just started
# This uses the jobId from the response above
GET {{host}}/api/jobs/{{startJob.response.body.$.jobId}}
Accept: application/json

###
# 4) Get images for the started job 
GET {{host}}/api/jobs/{{startJob.response.body.$.jobId}}/images
Accept: application/json

###
# 5) List all jobs
GET {{host}}/api/jobs
Accept: application/json

###
# 6) Get results (legacy / optional) for the job  just started
GET {{host}}/api/results/{{startJob.response.body.$.jobId}}
Accept: application/json

###
# 7) Debug queues (may only work locally or if exposed)
GET {{host}}/api/debug/queues
Accept: application/json